command_timeout = 5000

format = """
[]({{start}})\
$os$username\
[](bg:{{tertiary}} fg:{{start}})\
$directory\
[](fg:{{tertiary}} bg:{{primary}})\
$git_branch$git_status\
[](fg:{{primary}} bg:{{primary}})\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
[](fg:{{primary}} bg:{{primary}})\
$docker_context$nix_shell$direnv\
[](fg:{{primary}} bg:{{secondary}})\
$cmd_duration\
[](fg:{{secondary}} bg:{{secondary}})\
$time\
[ ](fg:{{secondary}})\
$line_break\
$character\
"""

[os]
disabled = false
style = "bg:{{start}} fg:{{close}}"

[os.symbols]
NixOS = "󱄅"
Macos = "󰀵"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:{{start}} fg:{{text_invert}}"
style_root = "bg:{{start}} fg:{{text_invert}}"
format = "[ $user ]($style)"

[directory]
style = "bg:{{tertiary}} fg:{{text_invert}}"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "
Developer = "󰲋 "

[git_branch]
symbol = ""
style = "bg:{{primary}}"
format = "[[ $symbol $branch ](fg:{{text_invert}} bg:{{primary}})]($style)"

[git_status]
style = "bg:{{primary}}"
format = "[[($all_status$ahead_behind )](fg:{{text_invert}} bg:{{primary}})]($style)"

[nodejs]
symbol = ""
style = "bg:{{primary}}"
format = "[[ $symbol( $version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[c]
symbol = " "
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[rust]
symbol = ""
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[golang]
symbol = " "
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[php]
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[java]
symbol = " "
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[kotlin]
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[haskell]
symbol = " "
style = "bg:{{primary}}"
format = "[[ $symbol ($version) ](fg:{{text_invert}} bg:{{primary}})]($style)"

[python]
style = "bg:{{primary}}"
format = "[[(\\($virtualenv\\) )](fg:{{text_invert}} bg:{{primary}})]($style)"

[docker_context]
symbol = " "
style = "bg:{{primary}}"
format = "[[ $symbol $context ](fg:{{text_invert}} bg:{{primary}})]($style)"

[nix_shell]
symbol = "󱄅 "
style = "bg:{{primary}}"
format = "[[ $symbol $name ](fg:{{text_invert}} bg:{{primary}})]($style)"
impure_msg = "impure"
pure_msg = "pure"
unknown_msg = ""

[direnv]
disabled = false
style = "bg:{{primary}}"
format = "[[ direnv ](fg:{{text_invert}} bg:{{primary}})]($style)"

[cmd_duration]
min_time = 500
show_milliseconds = true
style = "bg:{{secondary}}"
format = "[[  $duration ](fg:{{text_invert}} bg:{{secondary}})]($style)"
show_notifications = false
min_time_to_notify = 45000

[time]
disabled = false
time_format = "%R"
style = "bg:{{secondary}}"
format = "[[  $time ](fg:{{text_invert}} bg:{{secondary}})]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:{{start}})"
error_symbol = "[](bold fg:{{close}})"
vimcmd_symbol = "[](bold fg:{{text}})"
vimcmd_replace_one_symbol = "[](bold fg:{{tertiary}})"
vimcmd_replace_symbol = "[](bold fg:{{tertiary}})"
vimcmd_visual_symbol = "[](bold fg:{{text_invert_focus}})"
