# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@var/log" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@var/tmp" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/a3ff7994-0933-49db-bbb5-8574dca697b0";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51CE-09AA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/bf06b75e-cb40-408f-8fc9-c9af1088c8af";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2f2ffe97-2afb-4fc5-b4f3-1f1626aa24b8";
      fsType = "xfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
