backend = "glx";
vsync = true;

shadow = false;
fading = false;

corner-radius = 12;

rules = (
# Rounded corners exclude
  {
    match = "window_type = 'dock' || window_type = 'desktop' || override_redirect";
    corner-radius = 0;
  },
  {
    match = "fullscreen";
    corner-radius = 0;
  },

# Global unfocused treatment
  {
    match = "!focused && !group_focused";
    dim = 0.10;
  },

  # No dim for menu / launcher style windows
  {
    match = "override_redirect";
    dim = 0;
  },

# Always translucent
  {
    match = "class_g = 'XTerm' || class_g = 'kitty' || class_g = 'Emacs'";
    opacity = 0.90;
  },

# Translucent only when inactive
  {
    match = "!(focused || group_focused) && (class_g = 'discord' || class_g = 'TelegramDesktop')";
    opacity = 0.90;
  },
);
